accessControl:
    autologinAs: homeassistant
    autologinLocal: true
    localNetworks:
        - 172.30.32.2
folder:
    data: /data/.octoprint/data
    generated: /data/.octoprint/generated
    logs: /data/.octoprint/logs
    plugins: /data/.octoprint/plugins
    printerProfiles: /data/.octoprint/printerProfiles
    scripts: /data/.octoprint/scripts
    slicingProfiles: /data/.octoprint/slicingProfiles
    timelapse_tmp: /tmp
    timelapse: /data/.octoprint/timelapse
    translations: /data/.octoprint/translations
    uploads: /data/.octoprint/uploads
    virtualSd: /data/.octoprint/virtualSd
    watched: /data/.octoprint/watched
server:
    commands:
        serverRestartCommand: s6-svc -r /var/run/s6/services/octoprint
        systemRestartCommand: /restart.sh
        systemShutdownCommand: /shutdown.sh
webcam:
    ffmpeg: /usr/bin/ffmpeg
    snapshot: http://774437fd-mjpg-streamer:80/?action=snapshot
    stream: /webcam/?action=stream
